name: Deploy CloudFormation Template
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@vl 
      with:
        aws-access-key-id: ${{ secrets. AWS_ACCESS_KEY ID }} 
        aws-secret-access-key: ${{ secrets. AWS_SECRET_ACCESS_ KEY }}
        aws-region: us-east-1b

    - name: Deploy CloudFormation stack 
      run: |
        aws cloudformation deploy \
        --template-file /cloudformation.json \
        --stack-name your-stack-name \
        --capabilities CAPABILITY_NAMED_IAM
